### ISSUE TITLE
Can not run example

### ISSUE THREAD

**Issue by sywka** [asfernandes/node-firebird-driver-native#8]
After installation, I tried to run your [example ](https://github.com/asfernandes/node-firebird-driver-native#usage-example) and got an error:

> TypeError: Cannot read property 'getDispatcherSync' of undefined
    at new ClientImpl (C:\Users\sywka\Desktop\gdmn\gdmn-db\node_modules\node-firebird-driver-native\dist\lib\client.js:27:39)
    at Object.createNativeClient (C:\Users\sywka\Desktop\gdmn\gdmn-db\node_modules\node-firebird-driver-native\dist\lib\client.js:19:12)
    at test (C:\Users\sywka\Desktop\gdmn\gdmn-db\dist\index.js:18:50)
    at Object.<anonymous> (C:\Users\sywka\Desktop\gdmn\gdmn-db\dist\index.js:37:1)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)

Installed as follows: 
`npm install --global --production windows-build-tools`
`npm install --global node-gyp`
`npm install --save node-firebird-driver-native`

What could be the problem?

And can you commit [test ](https://github.com/asfernandes/node-firebird-driver-native/blob/master/src/test/test.ts#L3)folder with the other examples?

**Comment by asfernandes** [comment]
`getDefaultLibraryFilename()` requires Firebird `fbclient.dll` library in the PATH. Is it?

Or you should pass its full path instead of using `getDefaultLibraryFilename()`.

**Comment by sywka** [comment]
Solved, thanks.

**Comment by gsbelarus** [comment]
It should be printed all over that native driver REQUIRES FB 3.0 or newer fbclient.dll. It WILL NOT work with FB 2.5 library.
